# Generated by Django 6.0.4 on 2026-04-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_classroom_classroommember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=11, null=True, unique=True, verbose_name='手机号'),
        ),
    ]
