# Generated by Django 6.0.4 on 2026-04-18 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_phone_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.TextField(blank=True, default='', verbose_name='API Key（加密存储）')),
                ('tag_model', models.CharField(default='qwen-plus', max_length=100, verbose_name='标注模型')),
                ('gen_model', models.CharField(default='qwen-plus', max_length=100, verbose_name='出题模型')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户AI配置',
                'db_table': 'user_ai_config',
            },
        ),
    ]
