# Generated by Django 6.0.4 on 2026-04-11 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GespLevel',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='级别')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('exam_duration', models.PositiveIntegerField(default=90, verbose_name='考试时长(分钟)')),
                ('total_questions', models.PositiveIntegerField(default=50, verbose_name='考试题目数')),
                ('pass_score', models.PositiveIntegerField(default=60, verbose_name='及格分')),
            ],
            options={
                'verbose_name': 'GESP级别',
                'verbose_name_plural': 'GESP级别',
                'db_table': 'gesp_level',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='章节名称')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='knowledge.gesplevel', verbose_name='级别')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
                'db_table': 'chapter',
                'ordering': ['level', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='知识点名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='简要说明')),
                ('content', models.TextField(blank=True, default='', verbose_name='讲解内容(富文本)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='knowledge.chapter', verbose_name='章节')),
            ],
            options={
                'verbose_name': '知识点',
                'verbose_name_plural': '知识点',
                'db_table': 'knowledge_point',
                'ordering': ['chapter', 'sort_order'],
            },
        ),
    ]
