# Generated by Django 6.0.4 on 2026-04-11 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.PositiveSmallIntegerField(choices=[(1, '单选题'), (2, '多选题'), (3, '判断题')], verbose_name='题目类型')),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, '简单'), (2, '中等'), (3, '困难')], default=1, verbose_name='难度')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='选项')),
                ('answer', models.CharField(max_length=10, verbose_name='正确答案')),
                ('explanation', models.TextField(blank=True, default='', verbose_name='解析')),
                ('source', models.CharField(blank=True, default='', max_length=100, verbose_name='来源')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('knowledge_points', models.ManyToManyField(blank=True, related_name='questions', to='knowledge.knowledgepoint', verbose_name='关联知识点')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='knowledge.gesplevel', verbose_name='级别')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'db_table': 'question',
                'indexes': [models.Index(fields=['level', 'question_type'], name='question_level_i_e32b56_idx'), models.Index(fields=['difficulty'], name='question_difficu_1f5c54_idx')],
            },
        ),
    ]
