# Generated by Django 6.0.4 on 2026-04-18 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_source_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, default='', max_length=300, verbose_name='API Key')),
                ('tag_model', models.CharField(default='qwen-plus', max_length=100, verbose_name='标注模型')),
                ('gen_model', models.CharField(default='qwen-plus', max_length=100, verbose_name='出题模型')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI配置',
                'db_table': 'ai_config',
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.PositiveSmallIntegerField(choices=[(1, '知识点标注'), (2, 'AI出题'), (3, '模型测试')], verbose_name='操作类型')),
                ('model', models.CharField(max_length=100, verbose_name='模型')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='输入Token')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='输出Token')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='总Token')),
                ('success', models.BooleanField(default=True, verbose_name='成功')),
                ('latency_ms', models.IntegerField(default=0, verbose_name='响应时间ms')),
                ('error_msg', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI用量日志',
                'db_table': 'ai_usage_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='question_level_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='question_level_src_active_idx',
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='最后修改者'),
        ),
        migrations.AddIndex(
            model_name='aiusagelog',
            index=models.Index(fields=['created_at', 'operation'], name='ai_usage_lo_created_d3fbd4_idx'),
        ),
    ]
