# Generated by Django 6.0.4 on 2026-04-19 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_aiusagelog_add_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusagelog',
            name='operation',
            field=models.PositiveSmallIntegerField(choices=[(1, '知识点标注'), (2, 'AI出题'), (3, '模型测试'), (4, 'AI题目讲解')], verbose_name='操作类型'),
        ),
        migrations.CreateModel(
            name='QuestionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.PositiveSmallIntegerField(choices=[(1, '答案有误'), (2, '题目表述不清'), (3, '选项有问题'), (4, '其他')], verbose_name='反馈类型')),
                ('content', models.TextField(blank=True, default='', verbose_name='反馈内容')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '待处理'), (1, '已处理'), (2, '已忽略')], default=0, verbose_name='处理状态')),
                ('admin_reply', models.TextField(blank=True, default='', verbose_name='管理员回复')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='questions.question', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='反馈用户')),
            ],
            options={
                'verbose_name': '题目反馈',
                'db_table': 'question_feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
