# Generated by Django 6.0.4 on 2026-04-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_add_question_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfig',
            name='pdf_model',
            field=models.CharField(default='qwen-vl-max', max_length=100, verbose_name='PDF识别模型'),
        ),
    ]
