# Generated by Django 6.0.4 on 2026-04-11 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStudyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_date', models.DateField(verbose_name='学习日期')),
                ('practice_count', models.PositiveIntegerField(default=0, verbose_name='练习题数')),
                ('correct_count', models.PositiveIntegerField(default=0, verbose_name='正确题数')),
                ('exam_count', models.PositiveIntegerField(default=0, verbose_name='模考次数')),
                ('study_minutes', models.PositiveIntegerField(default=0, verbose_name='学习时长(分钟)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '每日学习记录',
                'verbose_name_plural': '每日学习记录',
                'db_table': 'daily_study_log',
                'unique_together': {('user', 'study_date')},
            },
        ),
        migrations.CreateModel(
            name='UserKnowledgeMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attempts', models.PositiveIntegerField(default=0, verbose_name='总做题次数')),
                ('correct_count', models.PositiveIntegerField(default=0, verbose_name='正确次数')),
                ('mastery_level', models.PositiveSmallIntegerField(choices=[(0, '未学'), (1, '入门'), (2, '熟悉'), (3, '掌握'), (4, '精通')], default=0, verbose_name='掌握等级')),
                ('last_practiced', models.DateTimeField(blank=True, null=True, verbose_name='最近练习时间')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.knowledgepoint', verbose_name='知识点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '知识点掌握度',
                'verbose_name_plural': '知识点掌握度',
                'db_table': 'user_knowledge_mastery',
                'unique_together': {('user', 'knowledge')},
            },
        ),
    ]
