# Generated by Django 6.0.4 on 2026-04-11 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.PositiveSmallIntegerField(choices=[(1, '真题模拟'), (2, '随机组卷')], default=1, verbose_name='考试类型')),
                ('duration', models.PositiveIntegerField(verbose_name='考试时长(分钟)')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('total_score', models.PositiveIntegerField(default=0, verbose_name='总分')),
                ('earned_score', models.PositiveIntegerField(default=0, verbose_name='得分')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '进行中'), (1, '已交卷'), (2, '超时自动交卷')], default=0, verbose_name='状态')),
                ('switch_count', models.PositiveIntegerField(default=0, verbose_name='切屏次数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.gesplevel', verbose_name='级别')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '考试记录',
                'verbose_name_plural': '考试记录',
                'db_table': 'exam_record',
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(blank=True, default='', max_length=10, verbose_name='用户答案')),
                ('is_correct', models.BooleanField(null=True, verbose_name='是否正确')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='得分')),
                ('time_spent', models.PositiveIntegerField(default=0, verbose_name='答题用时(秒)')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='题目')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.examrecord', verbose_name='考试记录')),
            ],
            options={
                'verbose_name': '考试答题明细',
                'verbose_name_plural': '考试答题明细',
                'db_table': 'exam_answer',
            },
        ),
        migrations.CreateModel(
            name='ExamTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='试卷名称')),
                ('duration', models.PositiveIntegerField(verbose_name='考试时长(分钟)')),
                ('total_score', models.PositiveIntegerField(default=100, verbose_name='总分')),
                ('pass_score', models.PositiveIntegerField(default=60, verbose_name='及格分')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('template_type', models.PositiveSmallIntegerField(choices=[(1, '真题'), (2, '模拟卷')], default=1, verbose_name='试卷类型')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_templates', to='knowledge.gesplevel', verbose_name='级别')),
            ],
            options={
                'verbose_name': '试卷模板',
                'verbose_name_plural': '试卷模板',
                'db_table': 'exam_template',
            },
        ),
        migrations.AddField(
            model_name='examrecord',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.examtemplate', verbose_name='试卷模板'),
        ),
        migrations.CreateModel(
            name='ExamTemplateQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=2, verbose_name='分值')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_questions', to='exams.examtemplate')),
            ],
            options={
                'verbose_name': '试卷题目',
                'verbose_name_plural': '试卷题目',
                'db_table': 'exam_template_question',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='questions',
            field=models.ManyToManyField(through='exams.ExamTemplateQuestion', to='questions.question', verbose_name='题目'),
        ),
        migrations.AddIndex(
            model_name='examrecord',
            index=models.Index(fields=['user'], name='exam_record_user_id_ede699_idx'),
        ),
        migrations.AddIndex(
            model_name='examrecord',
            index=models.Index(fields=['status'], name='exam_record_status_f2e0fd_idx'),
        ),
    ]
