# Generated by Django 6.0.4 on 2026-04-11 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.PositiveSmallIntegerField(choices=[(1, '知识点专练'), (2, '随机组题'), (3, '错题复习')], verbose_name='练习类型')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='总题数')),
                ('correct_count', models.PositiveIntegerField(default=0, verbose_name='正确数')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='knowledge.gesplevel', verbose_name='级别')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '练习记录',
                'verbose_name_plural': '练习记录',
                'db_table': 'practice_session',
            },
        ),
        migrations.CreateModel(
            name='PracticeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(blank=True, default='', max_length=10, verbose_name='用户答案')),
                ('is_correct', models.BooleanField(null=True, verbose_name='是否正确')),
                ('time_spent', models.PositiveIntegerField(default=0, verbose_name='答题用时(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='题目')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='practice.practicesession', verbose_name='练习记录')),
            ],
            options={
                'verbose_name': '练习答题明细',
                'verbose_name_plural': '练习答题明细',
                'db_table': 'practice_answer',
            },
        ),
        migrations.CreateModel(
            name='MistakeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrong_count', models.PositiveIntegerField(default=1, verbose_name='累计错误次数')),
                ('last_wrong_answer', models.CharField(blank=True, default='', max_length=10, verbose_name='最近错误答案')),
                ('is_mastered', models.BooleanField(default=False, verbose_name='是否已掌握')),
                ('consecutive_correct', models.PositiveIntegerField(default=0, verbose_name='连续正确次数')),
                ('last_practiced_at', models.DateTimeField(blank=True, null=True, verbose_name='最近练习时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '错题记录',
                'verbose_name_plural': '错题记录',
                'db_table': 'mistake_record',
                'indexes': [models.Index(fields=['user', 'is_mastered'], name='mistake_rec_user_id_76e7f8_idx')],
                'unique_together': {('user', 'question')},
            },
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['user'], name='practice_se_user_id_15640b_idx'),
        ),
    ]
